# Generated by Django 5.2.5 on 2025-08-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('laborer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.laborer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.project')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('laborer', 'date', 'project')},
            },
        ),
    ]
